server:
  port: 8080
spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        partitions: 10
        replication.factor: 2
      auto-create: true
kafka:
  topic:
    name: account-balance