server:
  port: 8081
spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always